# Generated by Django 2.2.2 on 2020-02-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.CharField(max_length=100)),
                ('Address2', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualRevenue', models.FloatField()),
                ('MonthlyAverageBankBalance', models.FloatField()),
                ('MonthlyAverageCreditCardVolume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFRequestId', models.IntegerField()),
                ('RequestDate', models.CharField(max_length=50)),
                ('CFApiUserId', models.IntegerField(blank=True, null=True)),
                ('CFApiPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('IsTestLead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('DateOfBirth', models.CharField(max_length=100)),
                ('HomePhone', models.IntegerField()),
                ('SSN', models.IntegerField()),
                ('PercentageOfOwnership', models.FloatField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owners', to='loanapp.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('TaxID', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('NAICS', models.IntegerField()),
                ('HasBeenProfitable', models.BooleanField()),
                ('HasBankruptedInLast7Years', models.BooleanField()),
                ('InceptionDate', models.CharField(max_length=100)),
                ('Address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.BusinessAddress')),
                ('SelfReportedCashFlow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.CashFlow')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='Business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.ApplicationBusiness'),
        ),
        migrations.AddField(
            model_name='application',
            name='RequestHeader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.Header'),
        ),
    ]
